version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    depends_on:
      - backend
    container_name: levante_web
  backend:
    build: ./backend
    platform: linux/x86_64
    container_name: levante_api
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/app-backend
    environment:
      DATABASE_URL: mysql://root:password@db:3306/levante
      JWT_SECRET: supersecreto
      PORT: 3001
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    container_name: levante_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
